### ISSUE TITLE
How to run on Raspberry Pi / ARM based device?

### ISSUE THREAD

**Issue by Maxl94** [silvio/docker-languagetool#38]
Hello, 

when I try to start the container on my Raspberry Pi, it runs in the following issue:

```
Pulling languagetool (silviof/docker-languagetool:)...
latest: Pulling from silviof/docker-languagetool
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```

Here is my docker compose:
```
version: "3"

services:
  languagetool:
    image: silviof/docker-languagetool
    container_name: LanguageTool
    restart: always
    ports:
      - 8010:8010 
    environment:
      - langtool_languageModel=/ngrams  # OPTIONAL: Using ngrams data
      - Java_Xms=512m  # OPTIONAL: Setting a minimal Java heap size of 512 mib
      - Java_Xmx=1g    # OPTIONAL: Setting a maximum Java heap size of 1 Gib
    volumes:
      - ./ngrams:/ngrams
```

Could you add an ARM version?
